name: Deploy

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'feature/heroku-deploy'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a --recursive web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a --recursive web

      # - run: docker-compose --file docker-compose.ci.yml run ci
      # - name: Build, Push and Release a Docker container to Heroku.
      #   uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: 'task-manager-my-test-73'
      #     heroku_email: 'tony201994@mail.ru'
      #     branch: 'feature/heroku-deploy'
      #     remote_branch: 'feature/heroku-deploy'
      #     stack: heroku-20
      #     dockerfile_directory: ./
