name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
          MAILER_HOST: ${{ secrets.MAILER_HOST }}
          MAILER_USERNAME: ${{ secrets.MAILER_USERNAME }}
          ACTIVE_STORAGE_HOST: ${{ secrets.ACTIVE_STORAGE_HOST }}
        run: docker-compose --file docker-compose.ci.yml run ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
